/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { TeamOrgChartApiContext } from "./teamOrgChartApiContext";

class TeamOrgChartApi extends TeamOrgChartApiContext {
  // Operation groups
  chartDataApi: operations.ChartDataApi;
  chartsApi: operations.ChartsApi;
  positionsApi: operations.PositionsApi;
  remappingsApi: operations.RemappingsApi;

  /**
   * Initializes a new instance of the TeamOrgChartApi class.
   * @param [options] The parameter options
   */
  constructor(options?: Models.TeamOrgChartApiOptions) {
    super(options);
    this.chartDataApi = new operations.ChartDataApi(this);
    this.chartsApi = new operations.ChartsApi(this);
    this.positionsApi = new operations.PositionsApi(this);
    this.remappingsApi = new operations.RemappingsApi(this);
  }
}

// Operation Specifications

export {
  TeamOrgChartApi,
  TeamOrgChartApiContext,
  Models as TeamOrgChartApiModels,
  Mappers as TeamOrgChartApiMappers
};
export * from "./operations";
