/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as msRest from "@azure/ms-rest-js";


export const JsonChartItemViewModel: msRest.CompositeMapper = {
  serializedName: "JsonChartItemViewModel",
  type: {
    name: "Composite",
    className: "JsonChartItemViewModel",
    modelProperties: {
      id: {
        serializedName: "Id",
        type: {
          name: "Number"
        }
      },
      orgChartDefinitionId: {
        serializedName: "OrgChartDefinitionId",
        type: {
          name: "String"
        }
      },
      uniqueId: {
        serializedName: "UniqueId",
        type: {
          name: "String"
        }
      },
      managerId: {
        serializedName: "ManagerId",
        type: {
          name: "String"
        }
      },
      jsonData: {
        serializedName: "JsonData",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const VacantPositionViewModel: msRest.CompositeMapper = {
  serializedName: "VacantPositionViewModel",
  type: {
    name: "Composite",
    className: "VacantPositionViewModel",
    modelProperties: {
      name: {
        serializedName: "Name",
        type: {
          name: "String"
        }
      },
      managerId: {
        required: true,
        serializedName: "ManagerId",
        type: {
          name: "String"
        }
      },
      position: {
        serializedName: "Position",
        type: {
          name: "String"
        }
      },
      isTempPosition: {
        serializedName: "IsTempPosition",
        type: {
          name: "Boolean"
        }
      },
      expireDate: {
        serializedName: "ExpireDate",
        type: {
          name: "DateTime"
        }
      },
      uniqueId: {
        serializedName: "UniqueId",
        type: {
          name: "String"
        }
      },
      viewItem: {
        serializedName: "ViewItem",
        type: {
          name: "String"
        }
      },
      pictureUrl: {
        serializedName: "PictureUrl",
        type: {
          name: "String"
        }
      },
      isDepartment: {
        serializedName: "IsDepartment",
        type: {
          name: "Boolean"
        }
      },
      departmentTitle: {
        serializedName: "DepartmentTitle",
        type: {
          name: "String"
        }
      },
      departmentText: {
        serializedName: "DepartmentText",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ChartLayoutViewModel: msRest.CompositeMapper = {
  serializedName: "ChartLayoutViewModel",
  type: {
    name: "Composite",
    className: "ChartLayoutViewModel",
    modelProperties: {
      id: {
        serializedName: "Id",
        type: {
          name: "Number"
        }
      },
      orgChartDefinitionId: {
        serializedName: "OrgChartDefinitionId",
        type: {
          name: "String"
        }
      },
      uniqueId: {
        serializedName: "UniqueId",
        type: {
          name: "String"
        }
      },
      managerId: {
        serializedName: "ManagerId",
        type: {
          name: "String"
        }
      },
      order: {
        serializedName: "Order",
        type: {
          name: "Number"
        }
      },
      sortFlag: {
        serializedName: "SortFlag",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const ChartNode: msRest.CompositeMapper = {
  serializedName: "ChartNode",
  type: {
    name: "Composite",
    className: "ChartNode",
    modelProperties: {
      boxType: {
        readOnly: true,
        serializedName: "BoxType",
        type: {
          name: "Number"
        }
      },
      virtualLevel: {
        serializedName: "VirtualLevel",
        type: {
          name: "Number"
        }
      },
      searchName: {
        readOnly: true,
        serializedName: "SearchName",
        type: {
          name: "String"
        }
      },
      uniqueId: {
        serializedName: "UniqueId",
        type: {
          name: "String"
        }
      },
      managerId: {
        serializedName: "ManagerId",
        type: {
          name: "String"
        }
      },
      originalManagerId: {
        serializedName: "OriginalManagerId",
        type: {
          name: "String"
        }
      },
      managerDisplayName: {
        serializedName: "ManagerDisplayName",
        type: {
          name: "String"
        }
      },
      mappedId: {
        serializedName: "MappedId",
        type: {
          name: "String"
        }
      },
      mappedManagerDisplayName: {
        serializedName: "MappedManagerDisplayName",
        type: {
          name: "String"
        }
      },
      displayName: {
        serializedName: "DisplayName",
        type: {
          name: "String"
        }
      },
      jobTitle: {
        serializedName: "JobTitle",
        type: {
          name: "String"
        }
      },
      email: {
        serializedName: "Email",
        type: {
          name: "String"
        }
      },
      phone: {
        serializedName: "Phone",
        type: {
          name: "String"
        }
      },
      group: {
        serializedName: "Group",
        type: {
          name: "String"
        }
      },
      pictureUrl: {
        serializedName: "PictureUrl",
        type: {
          name: "String"
        }
      },
      isAssistant: {
        serializedName: "IsAssistant",
        type: {
          name: "Boolean"
        }
      },
      hasHiddenReports: {
        serializedName: "HasHiddenReports",
        type: {
          name: "Boolean"
        }
      },
      isCoordinator: {
        serializedName: "IsCoordinator",
        type: {
          name: "Boolean"
        }
      },
      isJointManager: {
        serializedName: "IsJointManager",
        type: {
          name: "Boolean"
        }
      },
      isDropLevel: {
        serializedName: "IsDropLevel",
        type: {
          name: "Boolean"
        }
      },
      isDropLevelParent: {
        serializedName: "IsDropLevelParent",
        type: {
          name: "Boolean"
        }
      },
      height: {
        serializedName: "Height",
        type: {
          name: "Number"
        }
      },
      width: {
        serializedName: "Width",
        type: {
          name: "Number"
        }
      },
      isDepartment: {
        serializedName: "IsDepartment",
        type: {
          name: "Boolean"
        }
      },
      isVacantPosition: {
        serializedName: "IsVacantPosition",
        type: {
          name: "Boolean"
        }
      },
      isTempPosition: {
        serializedName: "IsTempPosition",
        type: {
          name: "Boolean"
        }
      },
      vacantPosition: {
        serializedName: "VacantPosition",
        type: {
          name: "Composite",
          className: "VacantPositionViewModel"
        }
      },
      isChartAddition: {
        readOnly: true,
        serializedName: "IsChartAddition",
        type: {
          name: "Boolean"
        }
      },
      assistants: {
        readOnly: true,
        serializedName: "Assistants",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ChartNode"
            }
          }
        }
      },
      coordinators: {
        readOnly: true,
        serializedName: "Coordinators",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ChartNode"
            }
          }
        }
      },
      jointManagers: {
        readOnly: true,
        serializedName: "JointManagers",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ChartNode"
            }
          }
        }
      },
      tOCImpacts: {
        readOnly: true,
        serializedName: "TOC_Impacts",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      },
      tOCFields: {
        readOnly: true,
        serializedName: "TOC_Fields",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      },
      chartLayout: {
        serializedName: "ChartLayout",
        type: {
          name: "Composite",
          className: "ChartLayoutViewModel"
        }
      }
    }
  }
};

export const ChartDataView: msRest.CompositeMapper = {
  serializedName: "ChartDataView",
  type: {
    name: "Composite",
    className: "ChartDataView",
    modelProperties: {
      chartId: {
        serializedName: "chartId",
        type: {
          name: "String"
        }
      },
      startValue: {
        serializedName: "startValue",
        type: {
          name: "String"
        }
      },
      depth: {
        serializedName: "depth",
        type: {
          name: "Number"
        }
      },
      data: {
        serializedName: "Data",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ChartNode"
            }
          }
        }
      }
    }
  }
};

export const ChartDefinition: msRest.CompositeMapper = {
  serializedName: "ChartDefinition",
  type: {
    name: "Composite",
    className: "ChartDefinition",
    modelProperties: {
      orgChartDefinitionId: {
        serializedName: "OrgChartDefinitionId",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "Name",
        type: {
          name: "String"
        }
      },
      dataSourceType: {
        serializedName: "DataSourceType",
        type: {
          name: "String"
        }
      },
      isPublic: {
        serializedName: "IsPublic",
        type: {
          name: "Boolean"
        }
      },
      isPromoted: {
        serializedName: "IsPromoted",
        type: {
          name: "Boolean"
        }
      },
      maximumDepth: {
        serializedName: "MaximumDepth",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const CreateChartModel: msRest.CompositeMapper = {
  serializedName: "CreateChartModel",
  type: {
    name: "Composite",
    className: "CreateChartModel",
    modelProperties: {
      name: {
        serializedName: "Name",
        type: {
          name: "String"
        }
      },
      isPublic: {
        serializedName: "IsPublic",
        type: {
          name: "Boolean"
        }
      }
    }
  }
};

export const ChartPosition: msRest.CompositeMapper = {
  serializedName: "ChartPosition",
  type: {
    name: "Composite",
    className: "ChartPosition",
    modelProperties: {
      id: {
        serializedName: "Id",
        type: {
          name: "Number"
        }
      },
      name: {
        serializedName: "Name",
        type: {
          name: "String"
        }
      },
      managerId: {
        required: true,
        serializedName: "ManagerId",
        type: {
          name: "String"
        }
      },
      friendlyManagerId: {
        serializedName: "FriendlyManagerId",
        type: {
          name: "String"
        }
      },
      position: {
        serializedName: "Position",
        type: {
          name: "String"
        }
      },
      isTempPosition: {
        serializedName: "IsTempPosition",
        type: {
          name: "Boolean"
        }
      },
      expireDate: {
        serializedName: "ExpireDate",
        type: {
          name: "DateTime"
        }
      },
      uniqueId: {
        serializedName: "UniqueId",
        type: {
          name: "String"
        }
      },
      viewItem: {
        serializedName: "ViewItem",
        type: {
          name: "String"
        }
      },
      pictureUrl: {
        serializedName: "PictureUrl",
        type: {
          name: "String"
        }
      },
      isDepartment: {
        serializedName: "IsDepartment",
        type: {
          name: "Boolean"
        }
      },
      departmentTitle: {
        serializedName: "DepartmentTitle",
        type: {
          name: "String"
        }
      },
      departmentText: {
        serializedName: "DepartmentText",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const Remapping: msRest.CompositeMapper = {
  serializedName: "Remapping",
  type: {
    name: "Composite",
    className: "Remapping",
    modelProperties: {
      id: {
        serializedName: "Id",
        type: {
          name: "Number"
        }
      },
      uniqueId: {
        serializedName: "UniqueId",
        type: {
          name: "String"
        }
      },
      friendlyUniqueId: {
        serializedName: "FriendlyUniqueId",
        type: {
          name: "String"
        }
      },
      managerId: {
        serializedName: "ManagerId",
        type: {
          name: "String"
        }
      },
      friendlyManagerId: {
        serializedName: "FriendlyManagerId",
        type: {
          name: "String"
        }
      },
      mappedId: {
        serializedName: "MappedId",
        type: {
          name: "String"
        }
      },
      friendlyMappedId: {
        serializedName: "FriendlyMappedId",
        type: {
          name: "String"
        }
      }
    }
  }
};
