/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";

export const chartId: msRest.OperationURLParameter = {
  parameterPath: "chartId",
  mapper: {
    required: true,
    serializedName: "chartId",
    type: {
      name: "String"
    }
  }
};
export const depth: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "depth"
  ],
  mapper: {
    serializedName: "depth",
    type: {
      name: "Number"
    }
  }
};
export const remappingId: msRest.OperationURLParameter = {
  parameterPath: "remappingId",
  mapper: {
    required: true,
    serializedName: "remappingId",
    type: {
      name: "Number"
    }
  }
};
export const startValue: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "startValue"
  ],
  mapper: {
    serializedName: "startValue",
    type: {
      name: "String"
    }
  }
};
export const uniqueId: msRest.OperationQueryParameter = {
  parameterPath: "uniqueId",
  mapper: {
    required: true,
    serializedName: "uniqueId",
    type: {
      name: "String"
    }
  }
};
export const version: msRest.OperationURLParameter = {
  parameterPath: "version",
  mapper: {
    required: true,
    serializedName: "version",
    type: {
      name: "String"
    }
  }
};
